# Generated by Django 5.0.7 on 2024-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply_viewed_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_reply_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
