from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import JobPostCreateView, JobPostListView, JobPostDetailView, apply_to_job, CompanyApplicationsView, update_resume, update_application_status, UserListView

urlpatterns = [
    path('', views.index, name='index'),
    path('employer-dashboard/', views.employer_dashboard,
         name='employer_dashboard'),
    path('applicant-dashboard/', views.applicant_dashboard,
         name='applicant_dashboard'),
    path('applicant/register/', views.applicant_register, name='applicant_register'),
    path('employer/register/', views.employer_register, name='employer_register'),
    path('manager/register/', views.manager_register, name='manager_register'),



    path('fetch-countries-choices/', views.fetch_countries_choices,
         name='fetch_countries_choices'),
    path('fetch-countries/', views.fetch_countries,
         name='fetch_countries'),
     path('fetch/', views.fetch,
         name='fetchs'),
     path('fetch-choices/', views.fetch_choices,
         name='fetch_choices'),
    path('fetch-states/<str:country_code>/',
         views.fetch_states, name='fetch_states'),
    path('login/', views.custom_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('create-profile/', views.create_profile, name='create_profile'),
    path('create-company-profile/', views.create_company_profile,
         name='create_company_profile'),
    #     path('post-job/', views.post_job, name='post_job'),
    #     path('manage-jobs/', views.manage_jobs, name='manage_jobs'),
    path('edit-job/<int:job_id>/', views.edit_job, name='edit_job'),
    #     path('jobs/', views.job_list, name='job_list'),
    #     path('jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    #     path('apply/<int:job_id>/', views.apply_to_job, name='apply_for_job'),
    #     path('review-applications/', views.review_applications,
    #          name='review_applications'),
    path('update-company-profile/', views.update_company_profile,
         name='update_company_profile'),
    path('manage-jobs/', views.view_posted_jobs, name='view_posted_jobs'),
    path('edit-job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('update-application-status/<int:application_id>/<str:status>/',
         views.update_application_status, name='update_application_status'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
#     path('manage-user/<int:user_id>/', views.manage_user, name='manage_user'),
    path('job/create/', JobPostCreateView.as_view(), name='job_post_create'),
    path('jobs/', JobPostListView.as_view(), name='job_post_list'),
    path('job/<int:pk>/', JobPostDetailView.as_view(), name='job_post_detail'),
    path('job/<int:pk>/apply/', apply_to_job, name='apply_to_job'),
    path('applications/', CompanyApplicationsView.as_view(),
         name='company_applications'),
    path('application/<int:pk>/update_resume/',
         update_resume, name='update_resume'),
    path('applications/<int:pk>/accept/',
         views.accept_application, name='accept_application'),
    path('applications/<int:pk>/decline/',
         views.decline_application, name='decline_application'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:notification_id>/',
         views.notification_detail, name='notification_detail'),
    path('notifications/<int:notification_id>/delete/',
         views.notification_delete, name='notification_delete'),
    #     path('update-company-profile/', views.create_company_profile, name='update_company_profile'),
    path('company-profile/', views.view_company_profile,
         name='view_company_profile'),
    path('view-profile/', views.view_profile, name='view_profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('my-applications/', views.view_applications, name='view_applications'),
    path('jobs/delete/<int:job_id>/', views.delete_job, name='delete_job'),
     path('complaints/submit/', views.submit_complaint, name='submit_complaint'),
    path('complaints/', views.view_complaints, name='complaint_list'),
    path('manager/complaints/', views.view_all_complaints, name='complaint_lists'),
    path('complaints/<int:complaint_id>/response/', views.view_complaint_response, name='view_complaint_response'),
    path('complaints/<int:complaint_id>/respond/', views.respond_to_complaint, name='respond_to_complaint'),
    path('search/', views.search_jobs, name='search_jobs'),
    path('users/', UserListView.as_view(), name='user_list'),

]
